# This is a TOML document
# This document is a configuration file for yt2pt (Youtube to Peertube) mirror bot
# copy this file into the same directory and rename it "config.toml" and then modify config.toml as necessary.

# These are global configuration options, they apply to the bot as a whole and therefore all channels.
[global]
video_download_dir = "/home/tjiho/peertube/" # must be absolute path and user writable directory
use_pt_http_import = "true" # Peertube supports sending HTTP links to videos instead of downloading and uploading them. Use this option if you do not want to archive videos and have limited bandwidth. Setting this to true negates delete_videos as videos will not be downloaded, and disables transcoding.
delete_videos = "false" # Delete videos and metadata after upload to peertube, lowercase string
poll_frequency = 180 # poll frequency in minutes

# For every channel, a new [channel.x] entry must be added in [channel] in sequential numerical order starting at 0
# If you do not wish to append tags or descriptions then leave the quotes empty for those fields.
# All other fields must have values.
[channel]

[playlist]

[user]
    [user.0]
    name = "" # name of the channel, does not have to match YT or PT channel names
    yt_id = "LeMonde" # YT channel ID at the end of the url youtube.com/channel/<channel_id>
    peertube_instance = "https://peertube.com" # URL of peertube instance
    peertube_channel = "lemonde.fr" # peertube channel handle to upload video to
    peertube_username = "bob" # peertube username
    peertube_password = "password" # peertube password WARNING this file needs to be secure
    pt_channel_category = "news" # category of channel contents. see pt_languages_categories.txt for categories
    pt_tags = ["lemonde.fr","journalisme"] # tags to be added to uploaded video in Peertube, comma separated, max 5, between 2 and 30 char each
    default_lang = "french" # default language if YT channel does not have a language, see pt_languages.txt for available languages
    nsfw = "false" # lowercase string, is this channel NSFW?
    comments_enabled = "true" # lowercase string, do you want comments enabled in this channel?
    pt_privacy = 1 # 1 = public, 2 = unlisted, 3 = private, privacy for entire channel, default public
    description_prefix = "" # This description will be added to the beginning of the YT description
    description_suffix = "" # This description will be appended to the end of the YT description

